OpenPrinting/cups

ppdc/ppdc-import.cxx
See https://github.com/apple/cups/pull/5738
=> Fix leakage of ppd

backend/Makefile
See: https://github.com/apple/cups/pull/5827
=> backend/Makefile: Don't use libtool.

cups/ipp-vars.c
See https://github.com/apple/cups/pull/5793
=> ipptool: support mdns uris

backend/ipp.c
… removing a "Custom." prefix; do not choke if the GTK dialog sends "None" as phone number or pre-dial prefix
=> Debian: Fix fax numbers supplied via GTK print dialog

scheduler/Makefile
=> scheduler/Makefile: use new unit names in uninstall as well

conf/cupsd.conf.in
Issue [#82 ](https://github.com/OpenPrinting/cups/issues/82)
=> setting default browsing dependent on env variable

doc/cups.css
=> table header left aligned

doc/da/index.html.in, doc/de/index.html.in, doc/es/index.html.in, doc/fr/index.html.in, doc/ja/index.html.in, doc/pt_BR/index.html.in, doc/ru/index.html.in
to refer to OpenPrinting like in the english original index. french index is added, only partly translated. 
Result should be content equality of all index pages.
=> notices in localized index pages adjusted 

cups/http-addrlist.c
=> cups/http-addrlist.c: serr not defined, use sockerr

test/run-stp-tests.sh
=> run-stp-tests.sh: Add regression test for JobHistoryupdate after restart

configure, doc/da/index.html.in, doc/de/index.html.in, doc/es/index.html.in
We forgot to remove it in 3 different locales, so let us remove it there. I regenerated all files too using only autoconf so those changes are reflected in all files
=> Removed last remnants of CUPS_REVISION, since it is not used anymore

cgi-bin/template.c, cgi-bin/var.c, cups/auth.c, cups/getdevices.c, cups/ipp-file.c, cups/pwg-media.c, cups/tls-gnutls.c, filter/common.c, filter/rastertohp.c, scheduler/auth.c, scheduler/main.c, scheduler/util.c, systemv/cancel.c, systemv/cupstestppd.c, systemv/lpstat.c, tools/ippeveps.c
Some of the code is either dead code, redundant, or always true. Meaning they do not do anything since the cases were already dealt with in earlier parts of the code. It would be best to remove this code. 
Note that some of the code removal required a tiny bit of refactoring.
=> Remove redundant code

CHANGES.md, cgi-bin/admin.c, templates/printer-added.tmpl
Since we report the warning via lpadmin, we should do the same in Web UI.
=> choose-model.tmpl: Add warning about drivers deprecation

doc/help/man-ipptool.html
=> doc/help/man-ipptool.html: Fix links

scheduler/sysman.c
bzero has been deprecated since 2008
=> Replace the last bzeros with memset

scheduler/printers.c
Since drivers and raw queues going are deprecated and going to be
removed, this change will introduce a warning during cupsd's start.
This way we have all print queue installation options covered - lpadmin
and web ui were enhanced with warning in the past.
With this one merged, I would proceed with rc release - I hope I'll manage it this week (to match 2 week candency)
=> scheduler/printers.c: Add warning when loading printers

locale/cups_de.po
I have partially corrected existing translations and added new translations.
=> Improve German translation

cups/testi18n.c
Fix some minor resource leaks in test18n.c
=> Fix some minor resource leaks

cups/dest.c
Encountered in https://bugzilla.mozilla.org/show_bug.cgi?id=1747952
=> Fix leak of data.devices in cups_enum_dests

locale/cups_de.po
some new and missing translations added
=> updated de translations

cups/dest.c
Fixes #454 , the patch is created by Yair Yarom
(https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008053).
=> cups/dest.c: Write data into /etc/cups/lpoptions if we're root

berkeley/lprm.c
=> berkeley/lprm.c: Report error if -P doesn't have destination

.github/workflows/build.yml, .github/workflows/codacy-analysis.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverity.yml
The v2 API is deprecated. Update that and the setup-msbuild script used
=> Update GitHub Actions Checkout API

xcode/CUPS.xcodeproj/project.pbxproj
Remove dead file references and enable Dead Code Removal.
=> Update Xcode Project

cups/encode.c, scheduler/conf.c, scheduler/cups-deviced.c, scheduler/cups-exec.c, scheduler/file.c, scheduler/ipp.c, scheduler/main.c, scheduler/policy.c, scheduler/printers.c, scheduler/util.c
We can also use strtoul to convert strings since uid_t is unsigned.
=> Use uid_t to deal with uids instead of integers

cups/ipp.c
=> Fix ippDeleteValues corner case.

cups/ppd-cache.c
_ppdCacheGetInputSlot specifically requests the photo tray for paper sizes up to 5x7" if the client hasn't specified a media-source.  This can fail if the photo tray is physically smaller than 5x7 (for example, L-sized).
Instead of explicitly requesting the photo tray, try to request "auto" and fall back to "photo" if the printer doesn't provide that as an option.
Signed-off-by: Benjamin Gordon <bmgordon@chromium.org>
=> Update InputSlot selection for photo sizes (fixes #569)

cups/usersys.c
=> Fix data types on Windows

REPORTING_ISSUES.md
This should help us during communication with issue reporters.
=> REPORTING_ISSUES.md: Initial page

backend/usb-darwin.c
description is 256. However, buffer is 258, which is a problem because we are possibly exceeding the bounds of description when we access description[2 * i + 2] as i approaches 256. I refactored the code to make it more obvious that this should be avoided.
=> Fix bounds of description

backend/usb-darwin.c, cups/tls-darwin.c, cups/tls-sspi.c, filter/rastertoepson.c, scheduler/type.c
These checks just do extra work and have no effect
My justification:
https://godbolt.org/z/bP6GzzMza
=> Remove redundant checks

cups/tls-darwin.c
Make the err variable actually used and make secCert not const.
Also fixup httpSaveCredentials behavior to better match the changes made to err.
=> Resolve macOS build errors

man/mantohtml.c, scheduler/cups-driverd.cxx, scheduler/cupsfilter.c, scheduler/job.c, scheduler/type.c
This is more efficient than using the ! operator on older platforms.
=> Use XOR for integers that are always 1 or 0

tools/ipptool.c
=> Fix ipptool JSON output

scheduler/printers.c
When creating the IPP attrs based on the PPD file, if the PPD file supports custom page sizes update our media-col-database to contain a media-size attr with the min/max range.
=> Add custom page size values to media-col-database

cups/tls-darwin.c
Older versions of macOS do not support SecTrustCopyCertificateChain, so let's revert back to using SecTrustGetCertificateCount.
Fixes https://github.com/OpenPrinting/cups/issues/715
=> Fix compilation on older macOS versions

doc/help/man-ippeveprinter.html, man/ippeveprinter.1, man/mantohtml.c
=> Update ippeveprinter documentation

templates/printer-added.tmpl
Small fix for issue I have found during translating.
=> Fix broken bold tag

templates/choose-model.tmpl, templates/da/choose-model.tmpl, templates/de/choose-model.tmpl, templates/es/choose-model.tmpl, templates/fr/choose-model.tmpl, templates/ja/choose-model.tmpl, templates/pl/choose-model.tmpl, templates/pt_BR/choose-model.tmpl, templates/ru/choose-model.tmpl
The tag was never closed which produced invalid HTML. Luckily, this apparently has worked in all browsers.
=> Close OPTION HTML tag in printer driver list template

templates/choose-model.tmpl, templates/da/choose-model.tmpl, templates/de/choose-model.tmpl, templates/es/choose-model.tmpl, templates/fr/choose-model.tmpl, templates/ja/choose-model.tmpl, templates/pl/choose-model.tmpl, templates/pt_BR/choose-model.tmpl, templates/ru/choose-model.tmpl
Implement JavaScript filter for the PPD list in "Add Printer" and "Modify Printer" dialogs.
Sometimes there are too many models in the list that it's hard to find the one you want.
=> Web Ui: add filter by printer model in PPD driver list

backend/org.cups.usb-quirks
=> Add unidir USB quirk for Oki 407

cups/dest.c
The same as #887, but for 24.x branch
=> Fixed a couple of gcc warnings

scheduler/client.c
Web UI query on Classes/Printers should support:
- search for class/printer (/?QUERY=)
- manage printers (/?)
- listing jobs for the printer/class (/name?Which_jobs=completed)
- show NOT FOUND for non-existing destinations
The PR reworks the code to fix the 3rd point and support all other at the same time.
Fixes Apple/CUPS #6204
=> client.c: Fix web UI job queries on Classes/Printers pages

locale/cups_fr.po, templates/fr/choose-serial.tmpl, templates/fr/help-header.tmpl, templates/fr/printer-accept.tmpl, templates/fr/printer-cancel-jobs.tmpl
Here are a few corrections and additions for the French language. Thanks ;)
=> Update & fix French translations

scheduler/job.c
We already have the attr value.
=> Avoid second call to ippFindAttribute

scheduler/colorman.c
Handle memory by jumping to the end where the profile is released
=> Use goto for clearer handling of errors

desktop/cups.desktop.in
Also add to the Settings category, which is the recommended main category for hardware management tools. Reference: https://specifications.freedesktop.org/menu-spec/latest/additional-category-registry.html
=> desktop: Add Hungarian translation

locale/cups_ka.po
Hello,
Since there is no sync between weblate and github for cups, adding  file downloaded from weblate directly.
There are few caviats, but I'll fix them once I'll get correct translations of certain words.
Ekaterine
=> locale: Add Georgian translation

cups/json.c, cups/json.h
=> Use correct parameter name : rename 'value' to 'key'.Rename
