scheduler/Makefile
Fix --with-xinetd=/etc/xinetd.d not installing the cups-ldp xinetd configuration file.
This change is already shipping downstream for a long time now in source-based distributions like e.g. Gentoo Linux and Exherbo Linux.
=> Fix installation of xinetd configuration file for cups-lpd

cups/ppd-cache.c, scheduler/printers.c
The PPD generation code now works for printers that support a single
output bin. Also the PPD parsing code now parses the cupsPrintQuality
field which is generated by the PPD generation code.
=> Fix handling of the output-bin and print-quality IPP attributes

backend/Makefile, scheduler/cups-deviced.c, scheduler/job.c
This is needed:
- to comply with Debian Policy
- because it is both nonsensical to not do so
- it also breaks system checkers, bug reporting, etc
Bug: https://github.com/apple/cups/issues/2935
Bug-Debian: https://bugs.debian.org/410171
=> Debian: Install root backends world-readable

cups/ppd-cache.c
When I create a CUPS queue with a PPD file with choice names "Tray-1", "Tray-2",
... in the InputSlot option CUPS translates these names to double-dashed IPP
attribute names: "tray--1", "tray--2", ... in the "media-source" attribute, both
when passing a job to the printer with the IPP backend, making the printer
ignore the tray choice, and also when answering a get-printer-attributes IPP
request from a client. This happens when in the PPD a dash is followed by a
digit, as the pwg_unppdize_name() function in cups/ppd-cache.c inserts a dash
whenever a non-digit is followed by a digit in the PPD name. As IPP attribute
names generally never have double-dashes and also no dashes in the beginning or
the end of the name, I have modified the pwg_unppdize_name() function
appropriately.
Bug: …
=> Debian: Fix conversion of PPD InputSlot choice names

scheduler/client.c
When running it without arguments it is supposed to read the local CUPS's
cupsd.conf and show a summary of the setting. in CUPS 2.3.1 it shows a mess
with a lot of HTML inside and this is due to the fact that when loading the
file via HTTP using the /admin/cups/cupsd.conf path the scheduler calls the
admin.cgi program which returns the admin front page of the web admin
interface. cupsctl then tries to interpret that as the config file and displays
garbage. Even worse is if you run cupsctl with command line argument (one of
the five switches or a key=value pair) to change a setting. It seems to load
cupsd.conf again and gets again the HTML code of the web interface page.
cupsctl tries to interpret this again, producing garbage, adds the
user-supplied setting and writes all this back into …
=> Debian: Fix scheduler cupsd.conf load

backend/snmp.c
… of HP and Ricoh to obtain the device IDs of network-connected
printers. This way we get more reliable information about make and model
and in addition the supported page description languages, which allows one to
identify whether an optional PostScript add-on is installed or for an
unsupported printer which generic PPD is the best choice (requested by
Ricoh).
Bug: https://github.com/apple/cups/issues/3552
=> Debian: Let snmp backend also use manufacturer-specific MIBs

scheduler/org.cups.cups-lpd.socket, scheduler/org.cups.cupsd.path.in, scheduler/org.cups.cupsd.service.in, scheduler/org.cups.cupsd.socket.in
Debian (and all systemd Linux'es) expect `systemctl status cups.service`.
The renaming is only done _within_ the files (to fix relationships), as Debian renames them at install time. But we could rename them too, of course.
=> Debian: Rename the systemd service file from org.cups.cups.* to cups.*

scheduler/org.cups.cupsd.service.in
=> Debian: Add Requires=cups.socket to cups.service, to make sure they start in order

scheduler/conf.c
Do not use host names for broadcasting print queues 
managing print queues broadcasted from other servers by default. Many
networks do not have valid host names for all machines.
Bug-Ubuntu: https://bugs.launchpad.net/bugs/449586
=> Debian: Do not use host names for broadcasting print queues 

backend/ipp.c, scheduler/ipp.c
The fix is created by Bernhard Übelacker from apple/cups #5826.
The problem is described in detail [here](https://github.com/apple/cups/issues/5826). I just removed:
```
--- a/backend/ipp.c
+++ b/backend/ipp.c
@@ -3026,6 +3026,7 @@ report_attr(ipp_attribute_t *attr)        /* I - Attribute */
valptr += strlen(valptr);
break;
+      case IPP_TAG_STRING :
default :
/*
* Unsupported value type...
```
from the original patch - it looks okay without it (since the attribute is found as IPP_TAG_STRING and the tag doesn't have a case in switch, it will fallback into ```default:``` case automatically).
Regarding [PWG standard](http://ftp.pwg.org/pub/pwg/candidates/cs-ippstate10-20090731-5100.9.pdf) IPP_TAG_STRING is the correct one - ```printer-alert``` is defined as octet-string (meaning …
=> backend,scheduler/ipp.c: Fix 'printer-alert' invalid free

conf/cupsd.conf.in, config-scripts/cups-defaults.m4
=> Debian: Allow configuration of MaxLogSize at configure-time

config-scripts/cups-directories.m4
Debian's kfreebsd-gnu architectures (`kfreebsd-amd64` and `kfreebsd-i386`) work as Debian/GNU systems, hence with a `/usr/lib/cups` SERVERBIN, not a `/usr/libexec/cups`.
* Debian kfreebsd-amd64's host system type is `x86_64-pc-kfreebsd-gnu`
* [FreeBSD's CUPS build log](http://beefy18.nyi.freebsd.org/data/head-amd64-default/p556876_s368287/logs/cups-2.3.3_1.log) shows that it is `amd64-portbld-freebsd13.0` for FreeBSD.
=> SERVERBIN: match host_os_name on *-gnu before *bsd* to catch kfreebsd-gnu's

config-scripts/cups-defaults.m4
Debian's kfreebsd-gnu architectures (kfreebsd-amd64 and kfreebsd-i386) work as Debian/GNU systems, hence with a 755 CUP_EXE_FILE_PERM, not 555.
Similar as #60
=> CUPS_EXE_FILE_PERM: also match host_os_name on *-gnu, to also catch kfreebsd-gnu

scheduler/cups.service.in
As reported in Debian's https://bugs.debian.org/977198 , some setups use nslcd.service for user account management. Starting CUPS after that makes sense.
=> Systemd: Let cups.service start after nslcd.service

CHANGES-OPENPRINTING.md, cgi-bin/help-index.c
Fixes a segfault in help.cgi, which happens if user tries to search in man pages.
Fedora bug [#1921881](https://bugzilla.redhat.com/show_bug.cgi?id=1921881)
=> cgi-bin/help-index.c: Check node->section before using it in strcmp()

cups/ppd-cache.c
The icon file is only used on macOS (in which case HAVE_APPLICATIONSERVICES_H is enabled).
=> Ignore the APPrinterIconPath PPD attribute

man/cups.1
It seems the cups.1 manpage has been wrongly pointing to client.conf in section 7 since 2014, while it was always shipped in section 5. Fix this.
See Debian bug: https://bugs.debian.org/982303
=> Let cups.1 point to client.conf.5, not client.conf.7

.github/workflows/build.yml
As #117 shows, some errors happen on 32bits architectures.
Altough Github actions doesn't allow native building on 32 bits, we can cross-build, using the Debian/Ubuntu cross-compilation capabilities.
=> Github Actions: Add cross-build to i686

cups/auth.c, scheduler/client.c
Fixes the infinite loop when "Negotiate" authentication is used and allows "Local" certificate based authentication when connecting to localhost:
```
Client                       CGI
Browser <- Remote conn -> admin.cgi <--- Localhost conn --->  Scheduler
|                           |                                    |
+ --- HTTP/POST /admin/ --> |                                    |
|                           + --- CUPS-Get-Devices ------------> |
|                           |                                    |
|                           | <-- 401 Unauthorized --------------+
|                           |     WWW-Authenticate:              |
|                           |       Negotiate, (PeerCred,) Local |
|                           |                                    |
| <-- …
```
=> Fix negotiate authentication between CGIs and scheduler

cups/ppd.c, doc/help/spec-ppd.html, filter/spec-ppd.shtml
Made `True` case-insensitive in
`AccurateScreensSupport`,
`ColorDevice`,
`ContoneOnly`,
`cupsFlipDuplex` and
`cupsManualCopies`
and corrected documentation for existing clients. 
solved issue [#93](https://github.com/OpenPrinting/cups/issues/93)
=> making True case-insensitive and correcting documentation for existing clients

ppdc/sample.drv
Here some missing labels to use the ZPL driver in production.
* A4 A5/A5 Rotated to use them as Laserprinter replacement
* 6x8 to print in rotated
* 8.5x1 to print in oversized
=> add some more ZPL labelsizes

backend/ipp.c
job_canceled can be -1, 0, or 1. 0 indicates no error, 1 indicates
that we were cancelled in normal operations (user cancelled from
computer) and -1 indicates cancelled by printer.  There is clearly
an assumption that -1 is false since there is a check for
job_canceled < 0 a few lines later.
=> backend/ipp: Change handling of job_canceled

CHANGES.md, config-scripts/cups-defaults.m4, scheduler/cups.service.in
The variable contains 'multi-user.target' if CUPS is configured with
enabled browsing or enabled web interface, empty otherwise.
=> cups.service.in: Add SYSTEMD_WANTED_BY variable

CHANGES.md, scheduler/log.c
Currently there is a difference in job log format based on where logs
are sent - the message contains `[Job N]` if sent to a file and it
doesn't contain the string if sent to syslog.
Though it can be seen as a duplicate of information, since the main
syslog system used (journald) is capable of filtering messages based on
JID, but having `[Job N]` string in logs in syslog is useful when you
need to debug complex issues and you need to see what happens in the
scheduler and in a specific job at the same time - f.e. at print
servers.
How to reproduce:
0) set error logs to syslog in /etc/cups/cups-files.conf
1) $ cupsctl --debug-logging
2) $ lp -d <queue> <file>
3) $ journalctl -u cups
Actual results:
Cannot distinguish logs from scheduler and from the job
Results after the patch:
Job logs …
=> scheduler/log.c: Use `[Job N]` even for syslog

config-scripts/cups-startup.m4, config-scripts/cups-threads.m4, configure
have_system should be have_systemd. have_thread should be have_pthread.
=> Fix misspelled variable names in configure script

scheduler/cups.service.in
Start cupsd after nss-user-lookup.target has been reached, instead of listing every service that could provide username resolution (sssd, ypbind, nslcd, etc.) to the "After=" line in the systemd unit file.
https://www.freedesktop.org/software/systemd/man/systemd.special.html says that nss-user-lookup.target
should be used as synchronization point for all regular UNIX user/group name service lookups. ... All services for which the availability of the full user/group database is essential should be ordered after this target, but not pull it in. All services which provide parts of the user/group database should be ordered before this target, and pull it in.
=> scheduler/cups.service.in: Use nss-user-lookup.target in "After="

scheduler/main.c
The commit 9bdea94b145 introduced a regression in job control and data
files cleanup. If user sets PreserveJobHistory and PreserveJobFiles,
prints a file and stops cupsd before files are cleaned up, the files
aren't removed after cupsd restarts and the timeouts for removal are
reached.
The files will be removed if user uses command 'lpstat -W completed -o'
or by another cupsd restart after time passes JobHistoryUpdate, so
workarounds exist, however the current behavior is strange :( .
=> scheduler/main.c: Set select timeout to JobHistoryUpdate again

config-scripts/cups-common.m4
We actually use dbus_thread_init_default() in the code, so we should
check for it during configuration.
=> cups-common.m4: Check for dbus_thread_init_default()

backend/org.cups.usb-quirks
Without it the printer gets stuck waiting for some kind of USB response from the computer 3/4 into the page. Right at the end of the job. Sometimes it moves the printing head once every few minutes, if we wait for 20-30 minutes it often finishes correctly. Which is unacceptable.
Using `no-reattach unidir` instead of only `unidir` seems to also work fine, but it seemed superfluous in my case, so try that if things are still wonky. Disconnecting the USB cable makes it stop the job instantly, spitting the rest of the page.
The same setup works on Windows just fine. Maybe adding the other MP2XX models into the list should be considered. In my case, until a few months ago printing via CUPS without any kinds of quirks seemed to work fine, so it seems like some kind of regression.
The credit …
=> Add the Canon PIXMA MP240 to the USB quirk list

cups/hash.c
This is one of the less offensive patches needed to compile modern CUPS on Mac OS X 10.4.
=> Fix build on ancient platforms lacking SHA224

backend/usb-darwin.c
pData is a void pointer, and even though the address at request.pData[2] is being cast to that of a const UInt8 pointer, the request.pData has to be converted first BEFORE doing any pointer arithmetic. For this reason, it is best to write this it as a pointer sum, rather than an array.
=> Fix undefined behavior regarding pData

scheduler/job.c
Printing banner pages with raw print files (but not on raw printers), causes only the banner to be printed.  The patch to fix https://github.com/apple/cups/issues/4782 caused a slight regression that re-introduced part of the issue described in STR #1933.  The gziptoany filter is invoked for multi-file jobs on raw queues, but not for raw files on a non-raw queue.
=> scheduler/job.c: use gziptoany for raw files (not just raw printers)

scheduler/client.c
Because of this bug, the two if branches were identical and the do while loop was only running once.
=> Fix bug that removes language instead of country code

cups/snprintf.c
A NULL check was forgotten to be placed despite every other operation to buffer checking for NULL first in the same function, but these checks do not account for evert possible branch path
=> Prevent writing to NULL if buffer is NULL

cups/ppd-util.c, cups/tempfile.c
`_CS_DARWIN_USER_TEMP_DIR` was introduced in the 10.5 SDK. Sandboxing was introduced in 10.6 so the generic /tmp location should be fine on earlier OS versions.
=> Fall back to /private/tmp on Mac OS X 10.4

backend/usb-darwin.c
bzero is deprecated and we should be using memset instead. I copied the changes from the darwin fork and put them here
=> Sync improvements from downstream darwin-usb

cups/tlscheck.c, ppdc/ppdc.cxx, ppdc/ppdhtml.cxx, ppdc/ppdi.cxx, ppdc/ppdmerge.cxx, ppdc/ppdpo.cxx
Almost every non-returning function has this qualifier, but not all. This should properly define them all as well as shrink the final binary a little bit.
=> Add _CUPS_NORETURN to missing functions

packaging/cups.list.in
Back in commit 123979a9db0cec406d710e3b89f351f2e98cb686, `libcupsimage.so.2` was moved from the `filter/` directory to the `cups/` directory.
But the EPM packaging file didn't get updated at the time, so a `make deb` etc. is failing.
This fixes the path in the packaging so that the packages create successfully.
=> Fix path to libcupsimage.so.2 in EPM packaging

CHANGES.md, templates/choose-model.tmpl
If device uri doesn't contain model name, `current_make_and_model` is
uninitialized during driver selection in CUPS Web UI.
The issue manifests itself during choosing IPP Everywhere driver, which
has the variable in its name, so it ends up into
`{current_make_and_model} - IPP Everywhere`.
Since we don't have any info about model at the time, I would propose to
just shorten the driver name for such cases. The PR works that way.
=> CUPS Web UI: Fix uninitialized variable during driver selection

cups/versioning.h
Allow building without the header (e.g. on pre-10.12 systems) via `_CUPS_SOURCE`
=> Only include os/availability.h if needed

ppdc/ppdc-source.cxx, ppdc/ppdc.cxx
The arguments being passed to the constructor of ppdcProfile are actually swapped. This patch fixes that issue.
=> Fix swapped arguments

scheduler/ipp.c
If a job is restarted with a `job-held-until` attribute that isn't `no-hold`, the job should be restarted and held, but it isn't.  To demonstrate this, I wrote a small program that will restart a print job:
```
$ cat restart-and-hold-job.c
#include <stdio.h>
#include <stdlib.h>
#include <cups/cups.h>
int main(int argc, char *argv[]) {
ipp_t*         request = NULL;
char           uri[HTTP_MAX_URI] = "";
int            job_id = 0;
job_id = atoi(argv[1]);
/*
* Restart but hold the job
*/
// Create request
request = ippNewRequest(IPP_RESTART_JOB);
sprintf(uri, "ipp://localhost/jobs/%d", job_id);
ippAddString(request, IPP_TAG_OPERATION, IPP_TAG_URI, "job-uri", NULL, uri);
ippAddString(request, IPP_TAG_OPERATION, IPP_TAG_NAME, "requesting-user-name", NULL, cupsUser());
// Hold job …
```
=> scheduler/ipp.c: Change job state to IPP_JOB_HELD when job is restarted with appropriate job-held-until attribute.

cups/options.c
when 1284id dosen't end with semicolon，_cupsGet1284Values() cannot get last key and value.
eg.
uos@uos-PC:/usr/lib/cups/backend/snmp 10.10.120.220
network socket://10.10.120.220 "Unknown" "FUJI XEROX ApeosPort-V 4070 v  3. 43.  0 Multifunction System" "MANUFACTURER:FUJI XEROX;MODEL:ApeosPort-V 4070" ""
=> fix _cupsGet1284Values

scheduler/job.c
The old behavior unconditionally cleared the "offline-report"
printer-reason unless the backend was 'usb:' or 'ippusb:' with the
assumption that these were the only two direct-connect USB backends
in use, with everything else being remote.
This is definitely not the case; putting aside proprietary 3rd-party
backends, there is Gutenprint's USB backend, which identifies itself
with 'gutenprint52+usb:' or 'gutenprint53+usb:' depending on the version.
So, generalize the rule to search for the string 'usb:' in the uri
instead, which will allow all three/four usb backends to use the
'offline-report' printer-reason.
(FWIW, I'm not happy with this approach; It seems to me that the
CorrectSolution(tm) is to track the device-class returned by the backend
at discovery time, and ignore …
=> Expand whitelist for use of "offline-report"

CHANGES.md, cups/auth.c, cups/cups-private.h, cups/cups.h, cups/usersys.c, cups/versioning.h
This PR just adds the new cupsSetOAuthCB API for CUPS 2.4. I've done a little prototyping with mOAuth to verify this does what we need it to do.
=> Initial implementation of OAuth client callback (Issue #100)

config-scripts/cups-compiler.m4
GCC can provide even stronger stack protection, let's use it if
available. Otherwise fall back to -fstack-protector.
I found this during development on centos stream 9 - I wasn't able to pass -fstack-protector-strong (which is one of the reqs in centos stream 9/RHEL 9) into compiled libcups.so.2, then found out gcc chose more generic -fstack-protector because of configure check.
=> cups-compiler.m4: Check for -fstack-protector-strong

cups/http-support.c
Earlier we applied DigestOptions only for devices which implement RFC
2617 or RFC 7616, this commit applies it even for RFC 2069 support.
This issue came up during CentOS Stream/RHEL 9 development, where MD5
digest is marked as insecure for authentication/authorization, so it
should be turned off in default configurations to prevent security
issues.
This PR is a preview how the fix should look if accepted - more I'm
looking for discussion whether we should tackle MD5 usage for devices
supporting only RFC 2069.
=> cups/http-support.c: Apply DigestOptions to RFC 2069 support

cups/getifaddrs-internal.h
Without this compile fails on systems withou getifaddrs as _CUPS_PRIVATE
is undefined. Found on Solaris 10.
=> cups/getifaddrs-internal.h: Include versioning.h if ! HAVE_GETIFADDRS

CHANGES.md, conf/cupsd.conf.in, config-scripts/cups-defaults.m4, configure
**Updated message:**
The option enables setting IdleExitTimeout to a desired value - f.e.
setting to zero will disable automatic shutdown, which is useful on servers,
where cupsd is expected to run even if there is no web interface, no jobs
and CUPS doesn't share queues.
_Original message:_
On servers, CUPS is expected to be running permanently, even if there
are no jobs and no web interface, and CUPS doesn't share queues.
The option will set IdleExitTimeout to 0 if used - if not used or used
with 'disable', it sets the directive to default 60s.
=> Add --with-idle-exit-timeout configure option

CHANGES.md, config-scripts/cups-defaults.m4, configure, scheduler/cups.service.in
cupsd can be killed by systemd if the daemon takes too much time when
starting - f.e. when loading many queues and/or not enough memory for
loading the daemon quicker.
TimeoutStartSec directive for systemd services defines the time after
which the daemon is killed - if set to 'infinity', a service is not
killed.
=> Add --with-systemd-timeoutstartsec configure option

config-scripts/cups-compiler.m4
The flag compiles but fails to link when the deployment target is OS X 10.4.
=> Confirm that `-Wl,-pie` links on Darwin

config-scripts/cups-network.m4
Tested locally; `configure` will need to be regenerated. Fixes https://github.com/OpenPrinting/cups/issues/301
=> Fix configure syntax error

config-scripts/cups-defaults.m4
There is no printers.target in systemd, only printer.target (see man bootup).
This regression was introduced in #143
=> Fix default wanted-by target to printer.target

cups/ppd.c
Hi,
valgrind on ppc64le arch complains about jump based on uninitialized memory in ppd.c
=> Fix uninit value based jump in ppd.c

templates/trailer.tmpl
Fix for #346 
Changed the copyright info from Apple Inc. to Open Printing on the pages.
=> Fixed footer message for web pages

.github/workflows/build.yml, CHANGES.md, INSTALL.md, config-scripts/cups-tls.m4, config.h.in, configure, cups/Makefile, cups/cups.h, cups/http-private.h, cups/tls-openssl.c, cups/tls.c, cups/tlscheck.c, vcnet/config.h, vcnet/cupstestppd.vcxproj, vcnet/ippeveprinter.vcxproj, vcnet/ippfind.vcxproj, vcnet/ipptool.vcxproj, vcnet/libcups2.vcxproj, vcnet/libcups2_native.nuspec, vcnet/libcups2_native.redist.nuspec, vcnet/packages.config, vcnet/testhttp.vcxproj, xcode/config.h
CUPS 1.2 had OpenSSL support, but we removed it in 1.3 because (at the time) OpenSSL was in rough shape. Things have changed.
=> Bring back OpenSSL/LibreSSL support

scheduler/printers.c
cupsdDeleteTemporaryPrinters() deletes temporary queues which their last
status was updated 1 minute ago or older. It doesn't take into account
the fact the printer can be processing a big print job and cupsd deletes
the temp queue either way.
The fix in the PR now set cupsd to ignore queues which are in processing
state. If the delay in job processing is caused by an error in printer,
the correct error should kick in IPP backend.
=> scheduler/printers.c: Don't remove processing temp queue

cups/tls-gnutls.c
The current mode for `gnutls_bye()` in client use cases strictly
follows TLS v1.2 standard, which in this particular part says:
```
Unless some other fatal alert has been transmitted, each party is
required to send a close_notify alert before closing the write
side of the connection.  The other party MUST respond with a
close_notify alert of its own and close down the connection immediately,
discarding any pending writes.  It is not required for the initiator
of the close to wait for the responding close_notify alert before
closing the read side of the connection.
```
and waits for the other side of TLS connection to confirm the close.
Unfortunately it can undesired for reasons:
- we support switching of TLS versions in CUPS, and this mode strictly
follows TLS v1.2 - so for older version …
=> cups/tls-gnutls.c: Use always GNUTLS_SHUT_WR

config-scripts/cups-sharedlibs.m4
The minimal configuration changes to CUPS for supporting AIX shared library generation.
Many thanks for your consideration.
Fixes: #389
=> AIX: Add DSOFLAGS and LDFLAGS for shared library support.

backend/snmp.c
=> Include <cups/getifaddres-internal.h> when getifaddrs() is not provided by OS

scheduler/ipp.c
To print to a temporary CUPS queue for a discovered IPP printer the client has to send an `IPP_OP_CUPS_CREATE_LOCAL_PRINTER` IPP request to the CUPS daemon with the details for creating the temporary queue. CUPS then calls its `create_local_printer()` function to actually create the queue. This is already automatically and correctly done if the client uses the convenience API of libcups.
The GTK print dialog does not use the convenience API though. It displays all IPP printers for which CUPS can create temporary queues correctly, but it fails on services which are only available on the local machine and not on the network (loopback interface, "localhost") whereas printing via temporary queue on network/remote services works perfectly.
The problem is that Avahi advertises the local …
=> For local services use "localhost" in device URI of temporary queue

cups/ppd-cache.c, scheduler/ipp.c
When we put print-color-mode as a default attribute, it always overrides
settings from print dialog. We need to respect those settings and
transform the known PPD options into print-color-mode options.
=> Don't override color settings from print dialog

CHANGES.md, scheduler/ipp.c
If a driverless printer has .local in its URI, we resolve the
URI and save the resolved one as new device URI. The problem was that
a local pointer was assigned to the structure which is passed to the
function as parameter, so the pointer became invalid once the execution
left the create_local_bg_thread() function.
We need to allocate the device URI via cupsdSetString() - the string is
then freed when the printer is deleted or cupsd shuts down.
Fixes #419.
=> scheduler/ipp.c: Allocate device_uri via cupsdSetString()

locale/cups_zh_CN.po
Corrected Simplified Chinese translations of page sizes and envelope sizes to match standards and reflect the original meanings. Corrected duplex translations. Replaced full-width brackets with half-width ones, which is the preferred practice of Chinese translation for FOSS projects.
=> Corrected Simplified Chinese translations of page sizes and others

config-scripts/cups-libtool.m4
Alternative fix for PR https://github.com/OpenPrinting/cups/pull/392.
Also see comment https://github.com/OpenPrinting/cups/pull/392#issuecomment-1124018535.
When the LIBTOOL variable is set in the user's environment the build will use libtool even when --enable-libtool-unsupported is not used.
This can lead to unexpected failures when LIBTOOL is set to rlibtool rather than GNU libtool.
To solve this the build now relies on the enable_libtool_unsupported varaiable set by --enable-libtool-unsupported.
Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=843638
=> config-scripts: Fix --enable-libtool-unsupported

CHANGES.md, backend/org.cups.usb-quirks
I would commit this directly to OpenPrinting/cups, but I got:
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:OpenPrinting/cups.git
! [remote rejected]     master -> master (protected branch hook declined)
=> Adds USB quirk for GoDEX label printers (fixes #440)

cups/dest.c
The current code of `cupsGetNamedDest()` doesn't look up on network for
a default printer. The result is a temporary queue cannot be set as a
default printer.
Fixes #452
=> cups/dest.c: Look for default printer on network as well

scheduler/ipp.c
If a client uses PPD option ColorModel (which is converted into
attribute to be sent via IPP) for changing the default color option
(which happens via CUPS-Add-Modify-Printer operation), we have to
convert ColorModel into print-color-mode attribute, so the
print-color-mode-default attribute gets updated.
The change survives reboot because print-color-mode is saved as an
option in printer's entry in /etc/cups/printers.conf.
=> scheduler/ipp.c: Convert incoming ColorModel attribute

.github/workflows/build.yml
@tillkamppeter IMO we can use 22.04 for github actions now, ack?
=> github actions: Use Ubuntu 22.04 for Linux

scheduler/client.c, scheduler/conf.c, scheduler/ipp.c, scheduler/job.c, scheduler/mime.h, scheduler/printers.c
If multiple create_local_bg_thread threads are spawned, they can fight
over MimeDatabase (specifically over MimeDatabase->srcs array), ending
up in SIGSEGV if one thread uses the array, but the other deletes it.
I chose to use RW locks for protecting the pointer - IMHO we benefit
from multiple threads being able to read in parallel.
=> scheduler: Protect MimeDatabase from parallel access (fixes #466)

scheduler/ipp.c
If the application sends PPD option, don't override it via IPP default option.
=> scheduler/ipp.c: Ignore some more IPP defaults (fixes #484)

locale/cups_de.po
"Default pitch" is "Voreingestellte Gradation"
"Neigung" doesn't fit, since that just describes the tilting of something, "Gradation" with its description fits better for character sizes.
=> Fix German translation

cups/pwg-media.c
A number of sizes that were added to ipp-registrations.xml after the initial PWG 5101.1-2002 document are not currently mapped.  When these sizes are mapped through a generated IPP Everywhere PPD and back to IPP media size names, they get changed into auto-generated self-describing names instead of the official registered names.
This change adds all* the missing names.  Most of them don't have official MediaOptions keywords, so the PPD names are mapped to dimensions.  With the updated mapping table, all of these sizes can roundtrip correctly.
This also fixes a missing unit and an incorrect name in two existing mappings for oe photo sizes.
* iso_id-3_88x125mm is not added because it duplicates the existing iso_b7_88x125mm size.
Signed-off-by: Benjamin Gordon <bmgordon@chromium.org>
=> Add missing registered media sizes to PWG mapping table

scheduler/cupsfilter.c
We mistakenly set filterfds[1 - current][0] = -1; twice instead of doing that and doing filterfds[1 - current][1] = -1;
=> [Mistake Bug-Fix]: Fix cupsfilter by setting both array elements to -1

backend/ipp.c, cups/tls-darwin.c, cups/usersys.c, scheduler/sysman.c
We should use SecTrustCopyCertificateChain and then access the CFArray instead of using the deprecated SecTrustGetCertificateCount
Use xpc_connection_send_message_with_reply_sync instead of xpc_connection_send_message_with_reply
This also gives us the added benefit of not risking priority inversion, since xpc_connection_send_message_with_reply_sync takes care of that already.
Finally, use RtlGetVersion instead of deprecated GetVersionExA.
=> Fix trivial deprecations

cgi-bin/admin.c
Use strtol only if server_port is null rather than waste time putting "0" in atoi, which always comes out as 0
=> Avoid passing a constant to atoi

cups/adminutil.c
This is just silly otherwise and it is causing unneeded compiler warnings
=> Replace else-if with else

cups/ppd-cache.c
Either the parameter being passed should be 6, not 7, because of the null terminator in the string literal, or strcmp should be used instead.
=> Change strncmp parameter

backend/ipp.c, backend/lpd.c, tools/ippeveps.c
Explicitly cast to unsigned char, and check for NULL before passing pointers to functions that expect nonnull.
=> Fix compiler warnings about non-null and casting

cups/file.c, cups/http.c, cups/ipp-file.c, cups/raster-interpret.c, cups/raster-stream.c
These variables were already in the target type anyway, or implicitly converted to void *.
=> Remove pointless casts

conf/cupsd.conf.in
With the current default configuration, someone can request to Find New Printers without being authenticated and with no way to be authenticated. Without authentication cups does not detects printers on the network. The person might not realize that it's because authentication is missing. It seems natural to always offer to authenticate when accessing the administration page.
Co-Authored-By: Dominic Mayers <dominic.mayers@meditationstudies.org>
=> Change cupsd.conf to force authentication when accessing administration

scheduler/printers.c
In `load_ppd()` we would set the `print-color-mode` to `monochrome` only if the device supported color printing and the default PPD choice for ColorModel was RGB - this broke settings for color printing for models, which use `CMYK` for ColorModel.
With this patch we check for CMYK as well.
CUPS 3.0-
=> scheduler/printers.c: Check for CMYK as well (fixes #421)

scheduler/subscriptions.c
Fixes https://github.com/NixOS/nixpkgs/issues/195090.
NixOS systems with Avahi enabled would previously spam the journal with
this log message once a second: this hides that spam behind the log level.
=> Increase log level for "Expiring subscriptions..."

cgi-bin/admin.c
=> Manually assign the two char literals instead of a memcpy

tools/ippevepcl.c
Especially since letter size is the most common size
=> Make Letter the default size if the other values do not fit

cups/testcups.c
dest is a pointer to a struct, not the array, which is dests.
Honestly, I have no idea how this even compiled in the first place. Yes I know this is testcups, but still.
=> Fix passing wrong variable to cupsGetOption in testcups

cups/ppd-attr.c
Cups currently displays "Xerox" instead of "Xprinter." This patch fixes this behavior.
=> Correctly display "Xprinter" instead of Xerox for Xprinter devices

.github/dependabot.yml
Dependabot will help you to keep you notified about new releases and help you update your workflows.
Interval is set to `monthly` so it won't make too much noise.
<details>
<summary>Original content</summary>
Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on shell scripts changed via PR and reports results directly in PR.
I saw that your scripts are in great shape, but I think that you might find `differential-shellcheck` action useful. It is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential- …
=> ci: Add Dependabot to keep GitHub actions up to date

backend/lpd.c, backend/socket.c, backend/usb.c, filter/commandtops.c, filter/gziptoany.c, filter/pstops.c, filter/rastertoepson.c, filter/rastertohp.c, filter/rastertolabel.c, filter/rastertopwg.c, monitor/bcp.c, monitor/tbcp.c
They both do the same thing, but the latter is more clear.
=> Change (argc < 6 || argc > 7) to (argc != 6 && argc != 7)

filter/rastertolabel.c
We check for it the line below, so let's remove it from the for-loop conditional
=> Remove redundant Canceled check

cups/ppd-util.c
This is safe to do since this function is not supposed to be exposed via the ABI, nor is there a pointer to this function, so as long as every other function in the file accommodates this change, nothing should happen.
In addition, depth is always 0 and only used for one debug print statement anyway, so we can and should remove it, instead of simply declaring it unused.
=> Remove useless depth argument from static function cups_get_printer_uri

scheduler/ipp.c
In the create_local_bg_thread() function for auto-generating a PPD file for a CUPS queue for a driverless printer, either via the "everywhere" model selection or an auto-created temporary queue we need to query the full capabilities information from the printer.
To get the full set of printer properties from a driverless IPP printer one does a "get-printer-attributes" IPP request with the attribute "requested-attributes" set to "all,media-col-database" (note that "all" does not include "media-col-database" because this attribute is often very long, it contains all valid combinations of media size, media type, media source, and margins). For some printers this fails and we fall back to just "all" and lose valuable information.
But some of those printers which do not support …
=> PPD for driverless IPP: Poll "media-col-database" separately if needed

cups/backchannel.c
Checking for merely (status < 0) is a bug because the check for timeout is deliberate.
Note that you have an if (timeout < 0) at the beginning
So if the timeout is set to a value, it should check for that value.
Co-Authored-By: aaaaaa123456789 <aaaaaa123456789@acidch.at>
=> Fix backchannel status checking bugs

backend/ieee1284.c, cups/dest-options.c, scheduler/conf.c
=> Fix-up ORs

cups/raster-stream.c
The first time `cups_raster_read` is called, both `r->bufptr` and `r->buffer` are NULL.  The calculation here then ends up looking like adding a size_t to a NULL pointer, which triggers the ubsan detector. Since we just want an offset, cast the pointer difference to ssize_t like the code already does a few lines below.
=> Fix UB in cups_raster_read debug message

cups/http-addr.c
Use a listen queue size of INT_MAX, which should default to the maximum supported queue size on the system.
This avoids the problem of the listening backlog queue getting full when there are too many requests at the same time. The problem was observed with the previous backlog size (128) by customers when submitting large batches of print jobs, resulting in some jobs getting lost.
=> cups/http-addr.c: Set listen backlog size to INT_MAX

tools/ippeveprinter.c
If a user passes the command by only its name, we have to check the path string we created instead of command string alone.
=> ippeveprinter.c: Check the created `path` string instead of `command`

cups/ppd-private.h, scheduler/printers.c
Otherwise, there's no way for clients to know the default media type or source unless they're using the legacy PPD API.
=> Include media-type and media-source in media-col-default

cgi-bin/admin.c, cups/string.c, man/mantohtml.c
This is much simpler to call over strtod and is supported on more older platforms.
=> Prefer atof over strtod

cups/tls-darwin.c
Currently, it returns -1 on error it seems, which is not how the function is documented to work.
=> cupsMakeServerCredentials should return 0 on failure, 1 on success

cups/file.c
Yes I know this shouldn't change the behavior in theory, but clang insists it does in practice, so to quiet the UBSan, I put parenthesis around pos - fp->bufpos.
=> UBSan: Contain pos - fp->bufpos in parentheses

cups/http.c
We are reading outside of the _fields boundaries and onto other fields when we iterate across all the fields, rather than comparing just those that are within _fields, and then always freeing the ones that are not.
This PR fixes that.
=> UBSan: Array over-read when operating on _fields

cups/request.c
size_t is unsigned, so let's not worry about signedness.
=> Cast to unsigned long instead of long for size_t

config-scripts/cups-compiler.m4, configure
GCC supports level 3 for some time, try using it.
=> configure: Raise FORTIFY_SOURCE level to 3

backend/dnssd.c, cgi-bin/var.c, cups/dest.c, cups/globals.c, cups/http.c, cups/ipp.c, cups/language.c, cups/ppd-cache.c, cups/ppd-emit.c, cups/raster-stream.c, cups/tls-sspi.c, scheduler/cert.c, scheduler/cups-driverd.cxx, scheduler/job.c, tools/ippfind.c
Many lines of code assume that malloc will not fail. In cases where it does, sometimes the program does not know, and as a result, memory can leak and more disastrous consequences can happen before the program ultimately finds something is wrong and then calls exit();
=> Improve state handling in cases of memory allocation failure

scheduler/printers.c
Colour mode selection is not persisted correctly across restarts. Current check in scheduler/printers.c:4573 is for `printer-color-mode`, but every other reference to this option is `print-color-mode` (no "er"). This was causing the selected colour mode to be reset to the PPD default on restart.
Changing to `print-color-mode` should fix this.
=> Fix check for existing color mode setting

cgi-bin/help-index.c
text is always more than or equal to ptr, so it will never underflow.
=> Wordlen should be a size_t, not an int

backend/usb-libusb.c
It was forgotten about, making the whole bytes addition useless.
=> Use print_ptr instead of print_buffer

backend/usb-darwin.c, cups/tls-darwin.c, ppdc/ppdc-catalog.cxx
There is an unlikely but still possible edge case where factories is leaked if the array being returned is not NULL but has a count of 0. This is because the CFRelease is at the end of the if statement brackets, when it should be at the end of the plugin bracket.
=> Free memory leaked by Darwin's Core Foundation

tools/ippeveprinter.c
There is no point in getting this data otherwise if the number of sources defined for the media_sources and for the input_tray differ.
=> Check that the number of trays is consistent before fetching anymore data

doc/help/man-ipptoolfile.html, man/ipptoolfile.5
I was exploring how to make a print job retry after failure, and quickly found the REPEAT and DELAY directives. REPEAT mentioned what the default value was, but DELAY had no such explanation readily available.
I am interpreting the `5000000` seen here as 5 seconds, though I was unsure if I was off by an order of magnitude: https://github.com/OpenPrinting/cups/blob/32572321f87b72d430ce4c20fb259c7ceee5ec7b/tools/ipptool.c#L5305 Use seems to indicate I am correct though :)
=> Document default repeat interval

.github/workflows/build.yml
- github action for Ubuntu 22.04 i386 fails during installing dependencies - try to upgrade the image before installing to prevent having an outdated image (in case Github doesn't update it...)
- use ubuntu-latest, so we automatically use the latest stable, but print out the pretty name in workflow to show which version it is (dont wanna to look up the names :))
=> workflows.yaml: Fix Github Actions and various fixes

config-scripts/cups-compiler.m4, config-scripts/cups-defaults.m4, config-scripts/cups-directories.m4, config-scripts/cups-gssapi.m4, config-scripts/cups-sharedlibs.m4, config-scripts/cups-threads.m4
Variable _host_os_name_ value has changed on Solaris from _sunos_ to _solaris_ some time ago. This change updates config-scripts to keep values used for Solaris 5.10 (sunos), but also sets relevant options on Solaris 5.11 (solaris). This change decreases the number of _configure_ options necessary to build CUPS on current Solaris.
Please consider merge.
Thank you,
m.
=> host_os_name value in config-scripts has changed to 'solaris'

cups/dest.c
Fixes regression created by #452 - in case there is no default
destination and `cupsGetNamedDest()` is called to get one (by calling it
with argument `name` as NULL), the function crashes.
It happens because we try to look for the default printer on the network
(where we access `data.name`, which is NULL, in callback), but we never
found out the printer's name.
Original fix by Emilio Cobos Alvarez.
=> dest.c: Call cupsEnumDests() only if data.name is not NULL (fixes #719)

cups/http-support.c
The bug during which certificates become corrupt was introduced in a521b235a1abc008cb0b2f490a765bb31e2ec14b. It turns out some data was not being truncated after being promoted to an integer, causing 1s to be ORed into the index number when they should not have been.
I only intended to remove the & 255 from the other side, where the & 63 would have rendered that operation redundant.
I apologize for this error. I made the appropriate changes I intended to make in this new PR.
Please merge and make a new release if possible.
=> Regression: Certificate data is corrupted during base64 conversion

CHANGES.md, cups/ppd-cache.c
Some printers are not able to print multiple files in one job via IPP Everywhere. Adding the PPD keyword enables the feature on all printers in exchange for performance degradation (there is a 1-2s pause between printed files).
Fixes #643
=> cups/ppd-cache.c: Put cupsSingleFile into generated PPD

CHANGES.md, cups/ppd-cache.c
Some printers are not able to print multiple files in one job via IPP Everywhere. Adding the PPD keyword enables the feature on all printers in exchange for performance degradation (there is a 1-2s pause between printed files).
Fixes #643
=>  cups/ppd-cache.c: Put cupsSingleFile into generated PPD

systemv/cancel.c
The command "cancel -x <job>" adds "purge-jobs true" to the Cancel-Job operation; however, the correct attribute to use for Cancel-job is "purge-job" (singular), not "purge-jobs" (plural).  As a result, job files are not removed from /var/spool/cups when "cancel -x <job>" is executed.
=> Use "purge-job" instead of "purge-jobs" when canceling a single job

locale/cups_pt_BR.po
Hello.
I'm willing to update the portuguese translations for cups, but it's a lot of work, just over 2500 msgs left.
I would like to know if you impose a line length limit, or there is some build step before submitting the PR.
I'm using checkpo.
=> Update pt-BR translation

scheduler/conf.c
In case cupsd can't open the cups-files.conf, the error message is lost if journal and syslog don't exist or work on system (usually in containers).
Log the error into stderr at this place to get the error message if needed.
=> scheduler/conf.c: Print to stderr if we don't open cups-files.conf

cups/md5.c, vcnet/cupstestppd.vcxproj, vcnet/ippeveprinter.vcxproj, vcnet/ippfind.vcxproj, vcnet/ipptool.vcxproj, vcnet/libcups2.vcxproj, vcnet/packages.config, vcnet/testhttp.vcxproj
- Fix MD5 on MacOS
- Update libressl version to fix Windows failure in CI
Both originate from master commits:
https://github.com/OpenPrinting/cups/commit/26836ad6312665091e5e47f547d2ff5e429ec031
https://github.com/OpenPrinting/cups/commit/60e0f489172c88f6a67a887180d7395c4d8afe52
=> Fix CI failures on MacOS and Windows

backend/lpd.c
In backend/lpd.c, if "reserve=rfc1179" is used in the Device URI, ports from 512-731 will be used instead of only 721=731 as per RFC 1179.
cups_rresvport() starts with the value of lport passed in to the function and decrements lport to 512 until an open port is found. Thus, if all ports from 731-721 are unavailable, cups_rresvport() will start binding to ports between 720-512.
This patch resolves this issue by adding a parameter to cups_rresvport() that defines the minimum port number that should be used and makes the appropriate changes in lpd_queue().
Resolves https://github.com/OpenPrinting/cups/issues/743
=> Fix behavior of "reserve=rfc1179" in backend/lpd.c

cups/hash.c
- I mustn't remove their support in patch release - this should happen in 2.5 only.
- I have put back support for several hashes as well - they should be removed in 2.5.
- restrict usage of second block hashing only if OpenSSL/LibreSSL/GnuTLS is available (since IMO I found its implementation useless for SSL libs, which will be removed in 2.5)
=> cups/hash.c: Put support for MacOS/Win SSL libs back

CHANGES.md, cups/dest.c
The current timeout is not able to list all network devices if there are many IPP services on mDNS (the tested number is 165 services).
Raising the timeout to 1s does not slow libcups if there are less services (Avahi returns earlier) or if Avahi does not run on the system (libcups cannot create an Avahi client in that case), and provides time frame for getting reasonable amount of IPP services (big enterprise servers will use permanent queues and printer profiles than mDNS).
Fixes #751
=> cups/dest.c: Raise timeout _CUPS_DNSSD_GET_DESTS

scheduler/job.c
With "PreserveJobHistory Off", LogLevel not set to debug (or debug2), and "LogDebugHistory 200" (the default), cupsdDeleteJob() frees the job history and then unloads the job.  However, unload_job() calls cupsdLogJob() which re-creates the job history and puts "Unloading..." into it because level (debug) is greater than LogLevel (warn) and LogDebugHistory is set to 200 messages by default.  Unused (and unreachable) job history is left behind, resulting in a memory leak.
The solution seems to be to unload the job before freeing the job history.
=> scheduler/job.c: unload job before freeing job history in cupsdDeletejob()

cups/ppd-cache.c
It fixes driverless printing on Pantum BM5100ADW Series and, probably, on many other devices.
- Without this parameter, /usr/lib/cups/filter/universal generates RGB image/urf even for monochrome printer
- Pantum BM5100ADW Series rejects to print these RGB images with the "Print job canceled at printer" status.
- Probably, this issue affects many other devices
See #804 for details.
=> cups/ppd-cache.c: Add cupsUrfSupported to generated PPD (see #804)

CHANGES.md, scheduler/colorman.c
Since the array `profiles` is set to use `strdup()` as a copy function, we
don't have to use `strdup()` on the element which is passed as parameter
of `cupsArrayAdd()` - using the `strdup()` as we used till now causes
memory leak.
Reproducer is the same as https://github.com/OpenPrinting/cups/pull/813
=> scheduler/colorman.c: Fix memory leak during creating color profile

doc/help/man-lpstat.html, man/lpstat.1, systemv/lpstat.c
`lpstat` does not have a way how to show successful jobs. One possible solution would be to rewrite the behavior of 'completed' type, but this can cause discrepancies in behavior which some users can expect.
Fixes #828
EDIT:
Now lpstat does filtering after receiving response, so no need for new support in cupsd - however lpstat still shows a new argument value.
=> lpstat.c: Implement successful filter for jobs

cups/raster-interpret.c
Fuzzer using `_cupsRasterExecPS()` found a way how to pass NULL into `scan_ps()`, causing crash - we have to sanitize the argument for NULL to fix it.
Fixes #831
=> raster-interpreter.c: Fix crash in 'scan_ps()' found by fuzzer

scheduler/colorman.c
The string which we add into array stays `const` after fixing #814 (because `strdup()`, which caused memory leak returned `char *`) and compiler fails because of it if it runs with '-Werror -Wall'.
=> scheduler: Fix build failure on Linux with '-Werror -Wall'

cups/http-addrlist.c
Some Linux kernel versions put POLLOUT|POLLHUP into revents when client tries to connect with `httpAddrConnect2()`, which makes the connection fail.
Let's check the option SO_ERROR before scratching the attempt - if there is no error, remove POLLHUP from revents.
I've re-purposed previously Solaris-only code to be used everywhere if the conditions are met - this should prevent bigger delays than necessary.
Slightly different issue than #827, but with similar symptoms (kernel sending POLLOUT|POLLHUP).
=> httpAddrConnect2: Check for error if POLLHUP is in valid revents

cups/dest.c, cups/dnssd.c
I found time to look why CI fails on Linux and came up with two fixes - for deadlock and infinite loop.
=> Fix CI for CUPS 2.5

cups/ppd-cache.c
Fixes #859
Windows 11 version 22H2 build 22621.2861 silently fails to add Mopria auto-discovered printer if it reports a number (a digit as a string) in media-source-supported field.
If you try to add such a printer using modern control panel, it will show endless "connecting…" message, and if you add it using old control panel, it would be added "successfully", but under "unrecognized" device type, and you won't be able to print on it.
Fix the issue by
* By comparing also by human-readable InputSlot name
* By mapping number to "tray-N" string
=> Report proper media-source-supported IPP field on numeric InputSlots

CHANGES.md, backend/ipp.c
If IP address was used with Kerberos, IPP backend retried connection indefinitely. The fix is to abort when we find out hostname is an IP address and we require Kerberos.
Fixes #838
=> backend/ipp.c: Fix infinite loop with Kerberos

CHANGES.md, backend/ipp.c
On older printers (ones which don't support IPP operation Create-Job) we concatenate job number and title into one string, which we use as IPP attribute job-name. If the original title was almost 255 chars, the joining the strings will overflow maximal required length for this attribute, and Validate-Job fails.
We could check whether the string is longer than 255 and cut it, but I chose to shrink the buffer to 256, since we already use `snprintf()` which will cut the string and put null terminator for us.
Fixes #644
=> backend/ipp.c: Fix printing jobs with long names on older IPP printers

cups/dest.c
In cups/dest.c:
dest.c:1830:21: warning: ‘%s’ directive argument is null [-Wformat-overflow=]
1733 |       DEBUG_printf(("1cupsGetNamedDest: Using name=\"%s\"...", name));
|                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This is really true, and gcc was smart enough to deduct it from context. Obviously, we meant to print dest_name here.
In cgi-bin/search.c:
search.c:191:29: warning: pointer ‘s’ may be used after ‘realloc’ [-Wuse-after-free]
191 |         sptr = temp + (sptr - s);
|                       ~~~~~~^~~~
The code is correct, but too hard for gcc to analyze. So code simplified a bit to make compiler happy.
=> Fixed a couple of gcc warnings

conf/pam.password, conf/pam.system, config-scripts/cups-pam.m4
This PR is actually based on one really old patch we have in Fedora, which enables possibility to use PAM modules password-auth or system-auth if they exist during compilation.
Those PAM modules looks to be used for remote, respective local authentication, in Linux. Would it be possible to add their support into CUPS?
=> Use PAM password-auth or system-auth if present

cups/ppd-cache.c
Some devices have `image/urf` in `document-format-supported`, but is missing `urf-supported` if AirPrint support is turned off, which breaks PPD generation.
Check for attribute `urf-supported` when we are about to decide whether the printer uses AirPrint, so in case the device supports another driverless standard, we can use it for PPD generation.
Fixes [Fedora issue](https://bugzilla.redhat.com/show_bug.cgi?id=2263053)
=> ppd-cache.c: Check for `urf-supported` if `image/urf` is found

cups/snmp.c
We can accept OID string as input in few cases (mainly via side channel) and if the crafted OID string is sent, internal function `asn1_size_oid()` can end up with stack buffer overflow.
The issue happens when one OID node is too large, or OID is invalid (no dots or ending with dots) - we can fix it in `_cupsSNMPStringToOID()` by checking for a dot or if the last source character is a dot (invalid OID), and by limiting integer for OID node to 0xffff.
Fixes #905
=> snmp.c: Validate input OID string for `_cupsSNMPStringToOID()`

scheduler/job.c
Before #832 most successfully finished jobs had incorrect job state reasons - try to fix them during loading the jobs.
=> scheduler: Fix reasons for previously printed jobs

scheduler/client.c
Sometimes headers are not correctly copied into response to the client (some are missing). It happens because `sent_header` is set prematurely before the actual send happens. The present code in affected `cupsdWriteClient()` scope looks like code remains from CUPS 1.6.3, where `cupsdSendHeader()` is called earlier and generates the required headers by itself - the current `cupsdSendHeader()` sends only the headers which are saved in array `fields`, so the premature setting of `sent_header` sometimes causes not having all headers in the response.
With the change, testing via curl gives reliable results all time.
=> scheduler: Fix sending response headers to client

.dockerignore, .gitignore, Dockerfile, INSTALL.md, docker-compose.yaml
This PR adds Dockerfile and Docker Compose configuration to streamline the process of setting up CUPS (Common Unix Printing System) in a Docker environment, making it easier for development purposes.
- Added a Dockerfile to define the environment and dependencies required for running CUPS.
- Included a Docker Compose configuration for orchestrating the build and execution of CUPS in a Docker container.
- Provided instructions in the INSTALL.md file on how to build, run, and access CUPS using Docker.
=> [Add] Dockerfile and Docker Compose for CUPS setup

scheduler/client.c
When adding a new printer a thread is created to handle PPD generation, and the requesting client connection might close while the thread is running. This commit prevents full connection cleanup until the thread is finished.
=> scheduler: Fix potential bug when adding new printers (Issue #934)

scheduler/ipp.c
The con->bg_pending value is used to indicate that the background thread has finished running and that the connection can be safely closed.
This commit makes the con->bg_pending = 0 only after the connection can be safely closed.
=> scheduler: Fix regression in background thread (Issue #934)

scheduler/client.c
We can use `?QUERY=` in URL for searching for destinations - allow it when checking whether the destination exists.
=> Fix HTTP query in web interface (fixes #954)

cgi-bin/var.c
In ```cgiGetTextfield()```, if the original value contains double quote, which is forbidden for text, we free the variable and move the next variable from array to its place. However, the return value still contains the original value of freed pointer, and shows garbage when used.
Set it NULL, since we don't have any value to return for the requested name.
=> cgi-bin/var.c: Fix return value if the text is invalid

cups/dest.c
=> cups/dest.c: Fix wrong cb parameter in `cupsConnectDest()` and return NULL pointer if connection cannnot be established

CHANGES.md, cups/ppd-cache.c
The PPD keyword got the option values concatenated together without commas, which broke filter processing in libcupsfilters
Sometimes more commas better commas :)
=> ppd-cache.c: Fix generating cupsUrfSupported (fixes #952)

cgi-bin/help.c
If a string was searched on CUPS Web UI help page, garbage was printed out in search box. It was because text field pointer was freed before and contained garbage - previously it was variable value which was allocated, so the string survived `cgCleanVariables(()`, but the text field is a pointer into form variables which gets cleaned up.
Fix is to use `strdup()` if `cgiGetTextfield()` returns non-NULL pointer. The binary exits shortly after either way, so memory is taken care of by OS.
=> cgi: Fix showing query string in Help

CHANGES.md, scheduler/conf.c, scheduler/main.c
If only the expected cups.sock is set as listener in cupsd.conf, the array Listeners was NULL. To prevent copying the code, do the array allocation earlier and have only one check for Listeners, in service_checkin() which is run every time cupsd starts.
Fixes #985
=> scheduler: Fix cupsd activated on-demand via socket

scheduler/client.c
Use the existing `ptr` instead of a new.
Fixes #1000
=> Do not use C99-only construct (fixes #1000)

cups/cups-private.h, cups/getdevices.c, cups/getputfile.c, cups/http-addr.c, cups/http.c, cups/ipp.c, cups/json.c, cups/ppd-util.c, cups/request.c
In case of internal errors, we use errno for generating error message, but there are cases (like operation timeout for listing drivers or models) when errno is zero.
We should take error from `http->error` if errno is zero, falling back to `Internal Server Error` if even `http->error` is 0 and still we have HTTP_STATUS_ERROR.
Fixes #893
=> request.c: Use errno only if it is non-zero (fixes #893)

CHANGES.md, scheduler/Makefile, scheduler/cups-lpdAT.service.in, scheduler/cups.service.in, scheduler/system-cups.slice
From the systemd documentation[1]:
> A slice unit is a concept for hierarchically managing resources of a group of processes.
Benefits of collecting our two systemd services into a slice include
* ease of configuring resource limits on the entire CUPS system,
* ``systemctl status`` showing the CUPS units in an indented subtree, making it more organized,
* and the possibility of viewing all interlaced logs from all of the CUPS daemons using ``journalctl -u system-cups.slice``.
[1]:
https://www.freedesktop.org/software/systemd/man/latest/systemd.slice.html or ``man systemd.slice(5)``
=> scheduler: add a systemd slice

cups/tls-gnutls.c
`credentials` changed type in 2.5, now gnutls pointer, which is needed for the mentioned function, is a member of new structure which is `credentials` now, so pass `credential->creds` to the function, otherwise it crashes.
Found out during running the test suite with gnutls enabled.
=> tls-gnutls.c: Pass gnutls pointer to `gnutls_credentials_set()`

scheduler/ipp.c
Related to #1033
PPD generator currently is capable to bypass missing attribute "media-col-database", if attributes "media-size-supported" or "media-supported" are present.
Although such devices do not pass any IPP Everywhere or AirPrint certifications, they exist in the wilderness.
=> scheduler: Tolerate devices breaking IPPEVE specs if possible

backend/ipp.c
xpc_dictionary_create has Nonnull annotated for some of its parameters. We should just do xpc_dictionary_create_empty to avoid warnings and be safe.
=> Use xpc_dictionary_create_empty to create empty dictionaries

scheduler/cups.service.in
Multiple functions that are called either implicitly or explicitly require a "roughly correct" CLOCK_REALTIME to behave.
=> cups.service.in: Order after time-set.target

cups/dest.c
We were still looking into ~/.cups/lpoptions as root in the function, which IMHO is not expected.
=> dest.c: Don't look for user config in cupsGetNamedDest as root

CHANGES.md, cups/ppd-cache.c
In the generated PPD, IPP finishings "bind" is supposed to map to "StapleLocation: BindAuto".  Similarly, "staple" is supposed to map to "StapleLocation: SingleAuto".  The code already handles this, except the lookup is blocked by a check that only accepts "staple-*" and "bind-*" prefixed versions.  Fix this by adding the bare versions to the existing checks.
Fixes issue #1073.
=> Support bare staple and bind finishings values

scheduler/ipp.c
If creating of permanent queue with IPP Everywhere model fails in separate thread, the print queue is created as raw.
It would be great if we remove such queue if creation fails, and marking them as temporary would make them to be removed automatically.
=> scheduler: Clean up failed IPP Everywhere permanent queues

templates/pt_BR/jobs.tmpl
Corrected from &Atilde;&Acirc;¡ to the correct &aacute; pt_BR translation for jobs.tmpl. To verify check printer.tmpl, which is right. usuário (user) and páginas (pages).
=> Update jobs.tmpl pt_BR template

cups/tls-gnutls.c
Some Linux systems provide a way how to control cryptography on system or service level via cryptographic policies. OpenSSL implementation reflects system changes to some degree, however GnuTLS implementation does not take system policy into account.
GnuTLS supports fallback mechanism, so we can fallback to NORMAL if @SYSTEM is not defined on the system.
Fortunately, the current GnuTLS implementation allows overrides via priority strings (so no "this cipher/hash is disabled" if we enabled them in our application by priority string), so allowing to honor system policy can save us work if someone wants to disable a specific cipher, so we don't have to implement it in libcups.
=> tls-gnutls.c: Use system crypto policy if available

CHANGES.md, scheduler/client.c
=> scheduler: Fix removing Server header from HTTP if requested

cups/http-private.h, cups/tls-gnutls.c, cups/usersys.c, doc/help/man-client.conf.html, doc/help/man-cupsd.conf.html, man/client.conf.5, man/cupsd.conf.5, scheduler/conf.c
In case using system crypto policy breaks communication with device irreversibly (f.e. if device does not support better key exchange algorithm), the new option value gives a way how to opt-out from crypto policy if user do not want to change default system crypto policy for the whole machine.
=> Add `NoSystem` SSLOptions value

cups/array.c
When delim variable has \0 value,
strchr() func switch end var to the end of string, set it to \0 and shift to next byte, which causes
heap overflow when new cycle runs
Fixes #1176
Signed-off by Kirill Furman <kir.furman@gmail.com>
=> Fix heap overflow in array.c

backend/ipp.c
Currently we show more detailed info about this error in debug logs, but since there are not many desktops to pick up our dBUS notification, it would be great to report it in CUPS log too.
=> backend/ipp.c: Raise alert if there is issue with cert

backend/ipp.c
It is possible for `format` to be NULL (as described in the function signature) which causes a segmentation fault when it is passed to `strcmp`. This patch changes the conditional to short-circuit if `format` is NULL and only call `strcmp` otherwise.
I discovered this issue while running a minimal setup with cups built and installed from the 2.4.x branch. Printing to an IPP printer server caused the IPP backend to crash before this change. I can provide more details on the environment if that is needed.
=> Avoid NULL strcmp argument

backend/org.cups.usb-quirks
This device is known to work with all quirks enabled, but exact quirk that helps is unknown. Let's enable all quirks for now.
=> Add Kyocera KM-1635 USB quirks

tools/ippfind.c
This PR supersedes #1211. It is build on a top of the latest 2.4.x changes to the `ippfind` and fixes remaining problems.
It includes two commits:
1. 8ac640e fixes a misuse of the Avahi API. There is no need to install our own poll_callback that enforces a 100 ms delay. I discussed this privately with @tillkamppeter, and he recommended submitting a PR based on that discussion.
2. f432557 modifies the end-of-search criteria to ensure reliable discovery. The previous version sometimes missed network devices, particularly when local devices (or a mix of devices already cached by Avahi and network devices pending discovery) were present.
For more details, please refer to the commit descriptions.
=> ippfind Avahi API mususe fix and discovery reliability improvement

config-scripts/cups-common.m4, config.h.in, cups/globals.c
Comparing effective and real uid/gid is not a proper way to check for SUID execution:
1. this does not consider file capabilities
2. this check breaks when NO_NEW_PRIVS is used as the Linux kernel resets effective ids during execve(); this means the check is false, but the process still has raised capabilities
For more details about the NO_NEW_PRIVS problem, check this post and the surrounding thread:
https://lore.kernel.org/lkml/20250509184105.840928-1-max.kellermann@ionos.com/
=> cups/globals: use getauxval(AT_SECURE) for SUID check

cups/encode.c, doc/help/man-lp.html, man/lp.1, scheduler/ipp.c, scheduler/job.c, scheduler/job.h, scheduler/printers.c
EDITED - see the old version in history.
Some printers do not take kindly newer PDF versions which results in
omitting font characters in the printout. Such jobs print fine as a
raster, however retrying as raster depends on benevolence of the printer
firmware what it counts as an unrecoverable printing error.
In the past, we preferred raster over PDF in cups-filters, causing other
issues like with finishings, or solutions like generating PCLm PPD were
mentioned, however it would require a way how to define for which models
it should be used, and take of such database.
Thus introducing `print-as-raster` job attribute, which makes the job
to be printed as raster, and `print-as-raster-default` printer attributes,
which makes any job coming into the printer object to be printed as raster. …
=> Introduce print-as-raster as printer/job attribute

scheduler/job.c
Currently if we load jobs from job.cache, we don't set correct times for `history_time` and `file_time`, resulting them in being 0 and the jobs avoids the cleanup by cupsd when needed, leading into eating up memory space.
It happens because none of the functions which set those job members are not called - `cupsdSetJobState()` is used when changing job states, `cupsdUpdateJobs()` during partial reload and `cupsdLoadJob()` is guarded by condition in `load_job_cache()`.
The fix is to change conditional in `load_job_cache()` which will cause loading of the job if cupsd is set to clean up job history, or if cupsd should clean up job files and the job still has some.
=> scheduler: Fix cleaning jobs by loading times when needed
